# Site settings
title: "RING18"
description: "septembeR IN Genève"
url: "http://ai-sf.it/ring18" # the base hostname & protocol for your site
destination: ../site/
locale: "it"

# Build settings
markdown: kramdown
future: true
permalink: /blog/:year/:month/:day/:title/
destination: _site


#facebook
fb_admins:
fb_appid:

#Collections
collections:
  events:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

gems:
 - jekyll-redirect-from
 - jekyll-sitemap
